({
  width: 48,
  height: 48,
  bpp: 1,
  buffer: E.toArrayBuffer(atob(
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAD/4AAAAAP/+AAAAB+APgAAAH4AB4AAA/gAAcAAB+AAAMAAHwAAAOAAPAAAAHAA" +
    "MAAADDAAcAAADDAAYAABgDAA4AxhgBgAwAxgABgAwYBgABgAwYBgABgAwABgAB" +
    "gAwANgABgAwANgYBgAxgBgYBgAxgBgABgAwBhgABgAwBhgBhgAwABgBjgA4ABg" +
    "AHgAcMBhgHAAOMBhgOAAPABgA+AAHwAAB8AAB4AAHwAAA////gAAAP//+AAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAA="
  ))
})
